---
- tasks: 
   - name: Generate configuration file
     template: src=/home/amit/git/My_Pynet/week5/video3/router1.j2 
                 dest=/home/amit/git/My_Pynet/week5/video3/{{item.hostname}}.txt
     with_items:
       - {hostname: pynet-rtr1, ip_addr: 1.1.1.1}
       - {hostname: pynet-rtr2, ip_addr: 1.1.1.2}
       - {hostname: pynet-rtr3, ip_addr: 1.1.1.3}
       - {hostname: pynet-rtr4, ip_addr: 1.1.1.4}
       - {hostname: pynet-rtr5, ip_addr: 1.1.1.5}

  hosts: local
